server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

management:
  endpoint:
    web:
      exposure:
        include: "*"
#Actuator

#spring:
#  security:
#    user:
#      name: capstone
#      password: capstone
#Security


h2:
  console:
    enabled: true

spring:
  jpa:
    show-sql: true